import './globals.css'
import Nav from '@/components/Nav'
import TotalCostCProvider from '@/contexts/CostContext';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TotalCostCProvider>
          <Nav />
          {children}
        </TotalCostCProvider>
      </body>
    </html>
  )
}
