import './globals.css'
import Nav from '@/components/Nav'

//Contexts
import ProjectProvider from "@/contexts/ProjectContext";
import StepProvider from '@/contexts/StepContext';
import CommentProvider from '@/contexts/CommentContext';
import UserProvider from '@/contexts/UserContext';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ProjectProvider>
            <StepProvider>
              <CommentProvider>
                <Nav />
                {children}
              </CommentProvider>
            </StepProvider>
          </ProjectProvider>
        </UserProvider>

      </body>
    </html>
  )
}
